### ISSUE TITLE
Slovak language support

### ISSUE THREAD

**Issue by Blarne** [allegro/tradukisto#12]
Slovak language support is very close to Czech.

**Comment by dorians** [comment]
I would like to add Slovak language but I don't know it. Could you provide code or at least some tests? :)

**Comment by Blarne** [comment]
Yes, no problem,
 i have done it without test now.

Mira

Dne 7. 9. 2017 5:10 odp. napsal uživatel "Dorian Sarnowski" <
notifications@github.com>:

**Comment by Blarne** [comment]
Hi,
Slovak language support implemented, created pull request to master (I
haven't rights for create branche feature/slovak-support).

Mira



2017-09-07 17:24 GMT+02:00 Míra Svoboda <ing.miroslav.svoboda@gmail.com>:
