### ISSUE TITLE
Russian language bug

### ISSUE THREAD

**Issue by mixamlv** [allegro/tradukisto#13]
While implementing Latvian test, I found a bug in Russian plural forms.
These are valid assertions which will fail if you add them to RussianValuesTest:
```
        21_000        | "двадцать одна тысяча"
        51_000        | "пятьдесят одна тысяча"
        481_000       | "четыреста восемьдесят одна тысяча"
```
I don't speak Polish language so I can't fix it without splitting SlavonicPluralFroms into Russian+fix and Polish as is.

**Comment by dorians** [comment]
I can't speak Russian so I have pretty much the same problem here :). Please split this class and create PR with this change. I'll see if it is possible to make this change common for this two languages.

**Comment by dorians** [comment]
Could you please create PR for this change only?
