### ISSUE TITLE
Add support for Japanese

### ISSUE THREAD

**Issue by tomasz-sieminski** [allegro/tradukisto#142]
- [x] I checked [other issues](https://github.com/allegro/tradukisto/issues) and ensured that there are no duplicates. 

**Context**
I would like to add support for Japanese numerals

**Comment by tabatad** [comment]
Hi @tomasz-sieminski !
I'm from Japan and I would like to help with Japanese support.
Could you assign some tasks to me since you have already started to developing it?

**Comment by tabatad** [comment]
Hi @jglaszka !
There is one person who has been working on this Issue ahead of me, but I have not received a reply and their branch updates seem to have stopped two weeks ago.
Could you assign this issue to me?

**Comment by jglaszka** [comment]
Hi @tabatad, we are open for your PR. @tomasz-sieminski and someone of our maintainers will take a look at your code.

**Comment by jglaszka** [comment]
@tabatad Hi. I just merged and released new version with your contribution. Thanks for creating a good piece of work! 🙏
