### ISSUE TITLE
Awesome dependency!

### ISSUE THREAD

**Issue by frankcastro** [allegro/tradukisto#27]
I love your code, but I'm trying to extend to create an AmericanValues really based on the EnglishValues except for the pound sign £, and use the $ sign.  This would be great if you had this.  Again, awesome library much nicer to use than ICU4J.

**Comment by wjur** [comment]
Thank you for your effort on this. It'll be fantastic if you can contribute.

**Comment by MaciejLipinski** [comment]
Hello @frankcastro, I know it's been a long time since you created this issue, but with the release of version 1.9.0 I added an American English converter. I hope you find it useful :)
