### ISSUE TITLE
Ukrainian language support

### ISSUE THREAD

**Issue by dorians** [allegro/tradukisto#3]

**Comment by dorians** [comment]
Verified test values:

Value | Words
-------- | -------------
0 | ноль 
1 | одна 
2 | две 
3 | три 
4 | четыре 
5 | пять 
6 | шесть 
7 | семь 
8 | восемь 
9 | девять 
11 | одиннадцать 
12 | двенадцать 
13 | тринадцать 
14 | четырнадцать 
15 | пятнадцать 
16 | шестнадцать 
17 | семнадцать 
18 | восемнадцать 
19 | девятнадцать 
10 | десять
20 | двадцать 
30 | тридцать 
40 | сорок 
50 | пятьдесят 
60 | шестьдесят 
70 | семьдесят 
80 | восемьдесят 
90 | девяносто 
21 | двадцать одна
37 | тридцать семь
43 | сорок три
58 | пятьдесят восемь 
69 | шестьдесят девять
76 | семьдесят шесть
82 | восемьдесят две
95 | девяносто пять
100 | сто 
200 | двести 
300 | триста 
400 | четыреста 
500 | пятьсот 
600 | шестьсот 
700 | семьсот 
800 | восемьсот 
900 | девятьсот 
111 | сто одиннадцать
272 | двести семьдесят две
387 | триста восемьдесят семь
448 | четыреста сорок восемь
569 | пятьсот шестьдесят девять
625 | шестьсот двадцать пять
782 | семьсот восемьдесят две
895 | восемьсот девяносто пять
999 | девятьсот девяносто девять
1 000 | одна тысяча
2 000 | две тысячи
5 000 | пять тысяч
7 634 | семь тысяч шестьсот тридцать четыре
24 190 | двадцать четыре тысячи сто девяносто 
653 000 | шестьсот пятьдесят три тысячи
123 454 | сто двадцать три тысячи четыреста пятьдесят четыре
700 000 | семьсот тысяч
999 999 | девятьсот девяносто девять тысяч девятьсот девяносто девять 
1 000 000 | один миллион
2 000 000 | два миллиона
5 000 000 | пять миллионов
23 437 219 | двадцать три миллиона четыреста тридцать семь тысяч двести девятнадцать 
100 000 000 | сто миллионов 
123 456 789 | сто двадцать три миллиона четыреста пятьдесят шесть тысяч семьсот восемьдесят девять
1 000 000 000 | один миллиард 
2 147 483 647 | два миллиарда сто сорок семь миллионов четыреста восемьдесят три тысячи шестьсот сорок семь

**Comment by Bodyash** [comment]
it`s not Ukrainian language

**Comment by dorians** [comment]
I don't speak Ukrainian. Could you provide valid test cases for this language?

**Comment by Bodyash** [comment]
Try this


0 | нуль
-- | --
1 | одна
2 | дві
3 | три
4 | чотири
5 | п`ять
6 | шість
7 | сім
8 | вісім
9 | дев'ять
11 | одинадцять
12 | дванадцять
13 | тринадцять
14 | чотирнадцять
15 | п'ятьнадцять
16 | шістнадцять
17 | сімнадцять
18 | вісімнадцять
19 | дев'ятнадцять
10 | десять
20 | двадцять
30 | тридцять
40 | сорок
50 | п'ятдесят
60 | шістдесят
70 | сімдесят
80 | вісімдесят
90 | дев'яносто
21 | двадцять одна
37 | тридцять сім
43 | сорок три
58 | п'ятдесят вісім
69 | шістдесят дев'ять
76 | сімдесят шість
82 | вісімдесят дві
95 | дев'яносто п'ять
100 | сто
200 | двісті
300 | триста
400 | чотириста
500 | п'ятсот
600 | шістсот
700 | сімсот
800 | вісімсот
900 | дев'ятсот
111 | сто одинадцять
272 | двісті сімдесят дві
387 | триста вісімдесят сім
448 | чотириста сорок вісім
569 | п'ятсот шістдесят дев'ять
625 | шістсот двадцять п'ять
782 | сімсот вісімдесят дві
895 | вісімсот дев'яносто п'ять
999 | дев'ятсот дев'яносто дев'ять
1 000 | одна тисяча
2 000 | дві тисячі
5 000 | п'ять тисяч
7 634 | сім тисяч шістсот тридцять чотири
24 190 | двадцять чотири тисячі сто дев'яносто
653 000 | шістсот п'ятдесят три тисячі
123 454 | сто двадцять три тисячі чотириста п'ятдесят чотири
700 000 | сімсот тисяч
999 999 | дев'ятсот дев'яносто дев'ять тисяч дев'ятсот дев'яносто дев'ять
1 000 000 | один мільйон
2 000 000 | два мільйони
5 000 000 | п'ять мільйонів
23 437 219 | двадцять три мільйони чотириста тридцять сім тисяч двісті дев'ятнадцять
100 000 000 | сто мільйонів
123 456 789 | сто двадцять три мільйони чотириста п'ятдесят шість тисяч сімсот вісімдесят дев'ять
1 000 000 000 | один мільярд
2 147 483 647 | два мільярди сто сорок сім мільйонів чотириста вісімдесят три тисячі шістсот сорок сім

**Comment by Aboruhen** [comment]
add in #21
