### ISSUE TITLE
Issues with French numbers

### ISSUE THREAD

**Issue by adrogon** [allegro/tradukisto#31]
French is a complicated language, and writing numbers to letters is filled with exceptions.

The library is currently failing on several cases, some of them being **very** basic.

- "21" returns `vingt-un`, should be `vingt-et-un` (same for 31, 41, etc.)
- "200" returns `deux cent`, should be `deux cents` (same for 300, 400, etc.)

Also, a rectification from 1990 made the syntax more straightforward, with everything being hyphened as long as it's not `million` or `milliard` (billions).

A personal preference would therefore to be compatible with the _latest update_ rather than the deprecated version, and "200" would then return `deux-cents`.

I'll write a PR with lots of failing tests.
I can't tell whether or when I'll be able to fix the production code to make them pass.

**Comment by wjur** [comment]
That's a valuable contribution! I see the FrenchValuesTest.groovy was missing some of the cases you mentioned. Thank you @adrogon in advance. I hope will find time to finish the PR. I'll try to be responsive as much as I can and support you if any issue arise. Let's continue the discussion on the PR's page.

**Comment by thomaszangerl** [comment]
> 
> 
> That's a valuable contribution! I see the FrenchValuesTest.groovy was missing some of the cases you mentioned. Thank you @adrogon in advance. I hope will find time to finish the PR. I'll try to be responsive as much as I can and support you if any issue arise. Let's continue the discussion on the PR's page.

We would also need correct French numbers, I already started working on a fix (shouldn't be too complicated). I modified the unit tests and the new code passes them.

Would you still accept a pull request for this issue?

**Comment by MaciejLipinski** [comment]
Merged @thomaszangerl 's https://github.com/allegro/tradukisto/pull/41
