### ISSUE TITLE
please add spanish support

### ISSUE THREAD

**Issue by fcarrero** [allegro/tradukisto#35]
please add spanish support

**Comment by MaciejLipinski** [comment]
We will try to address this. See:
https://github.com/allegro/tradukisto/tree/feature/spanish-support
https://github.com/allegro/tradukisto/pull/16
https://github.com/allegro/tradukisto/pull/20

**Comment by jglaszka** [comment]
Support was released in https://github.com/allegro/tradukisto/releases/tag/v2.6.0
