### ISSUE TITLE
1.10.3 version causing dependency issues for  com.google.common.collect package

### ISSUE THREAD

**Issue by srilavanyapaleti** [allegro/tradukisto#56]
Updating to the latest version of this library 1.10.3 from 1.3.0 causes issues importing the google collect packages when a maven build is run on a project using this library. The build wouldnt work unless an com.google.guava dependency is added to the parent pom. 

Some dev notes incase it is useful. There is a difference in pom between the two versions where 1.3.0 included a com.google.guava compile dependency while 1.10.3 is missing that dependency. 

<dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.1-groovy-2.4</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

**Comment by MaciejLipinski** [comment]
Thank you for pointing out the issue. It turns out it was present since `1.9.0` (and until `1.10.3`) because of changes in the publishing task.

As of `1.10.4` the issue is fixed and the dependency (`com.google.guava:guava`) is included in the jar.
