### ISSUE TITLE
Add Bulgarian support

### ISSUE THREAD

**Issue by gavrilovniki** [allegro/tradukisto#62]
I have working version, but don't have permission to push in feature branch.

**Comment by gavrilovniki** [comment]
> Hello, please fork the repository and create a pull request, see example: #49

https://github.com/allegro/tradukisto/pull/63

**Comment by gavrilovniki** [comment]
Hey @MaciejLipinski hope everything is good with you! Any updates on the PR?

**Comment by MaciejLipinski** [comment]
> Hey @MaciejLipinski hope everything is good with you! Any updates on the PR?

Hello, I will review it this week. Sorry for the delay!
